#+TITLE: Dot Files
#+AUTHOR: Oliver Taylor

I've learned a lot by reading other people's dot files,
I hope you can learn something from reading mine.

~oliver

** The Software I Use

You can find a detailed write-up of the software I use in =bootstrap.org=, but
these dotfiles are centered around just a few programs:

+ [[http://acme.cat-v.org][Acme]] :: a powerful text editor that takes the UNIX maxim (do one thing and
  do it well) to its logical extreme. If you haven't heard of Acme before [[https://research.swtch.com/acme][Russ
  Cox's tour of Acme]] gives a great overview of what it can do.
+ Shell Scripts :: these are a random collection of text-transformation
  scripts I've collected over the years, a few I wrote myself but most of them
  are ripped from other people's dotfiles (I hope you do the same!).
+ [[https://www.gnu.org/software/emacs/][Emacs]] :: My configuration file is long and contains lots of explanations for
  why I've configured it the way I have. In it I explain that I wrote it this
  way not for the 3 people who will ever stumble upon it but for me, to help
  me remember.
+ [[http://www.hammerspoon.org][Hammerspoon]] :: an app that lets you write code to control your computer.
  Lots of apps like this exist, but Hammerspoon is /crazy powerful/ and /crazy
  flexible/. I am not a real programmer, so the code therein might be a
  little... bad.
+ Vim :: I don't have a remarkable =vimrc= file but it's short and very vim-ish.

** Feedback

I can't imagine many people will ever read this, let alone want to talk to me
about it. But if you do please feel free to [[https://github.com/olivertaylor/dotfiles/issues][open an issue]].
