" General app prefs
" ---------------------------------------------------------------------------

set nocompatible                  " Must come first because it changes other options.
syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.
set modelines=0                   " Turn off modeline support
set encoding=utf-8                " Set default encoding
set ttyfast                       " Tell vim you're using a fast terminal.
set title                         " Set the terminal's title
set visualbell                    " No beeping.
set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location
set hidden                        " Handle multiple buffers better.
set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.
"set wildignorecase               " (7.3.107+) Ignore filename case in the command line.
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
set showmatch                     " Show matching brackets, etc.
set gdefault                      " Sets searches to be global (line) by default
set autoread                      " Tells vim to auto-read changes to the file from the disk.



" Editing Prefs
" ---------------------------------------------------------------------------
set autoindent                    " Turn on auto-indenting
set tabstop=4                     " Tab preferences
set shiftwidth=4
set softtabstop=4
set expandtab                     " Use spaces instead of tabs
set backspace=indent,eol,start    " Intuitive backspacing.

" Turn on spell-checking
setlocal spell spelllang=en_us

" Toggle spell-checking
nnoremap <leader>s :set spell!<cr>


" Display Stuff
" ---------------------------------------------------------------------------

set scrolloff=3                    " Show 3 lines of context around the cursor at all times.
set cursorline                     " Highlight the line the cursor is on

" WORD-WRAPPING
set formatoptions=tcrqn
set formatprg=par\ -w72rq
setlocal wrap 
setlocal linebreak

" SHOW 'NONAME' BUFFERS IN BUFEXPLORER 
let g:bufExplorerShowNoName=1


" COLORS
" ---------------------------------------------------------------------------

" ENABLE 256 COLORS
set t_Co=256

" THE STATUS BAR
set laststatus=2      "Always show status bar
set cmdheight=1       "Height of command typing area
set showcmd           "Shows your typing in Normal Mode

" COLOR SCHEME
set background=dark
colorscheme base16-ocean

" STATUS BAR COLORS - AFTER 'COLORSCHEME'
hi StatusLine ctermbg=1 ctermfg=00 term=none cterm=none
hi StatusLineNC ctermbg=08 ctermfg=07 term=none cterm=none
hi ModeMsg ctermbg=00 ctermfg=11 term=none cterm=none
hi LineNr ctermbg=10 ctermfg=8

" now set it up to change the status line based on mode
if version >= 700
  au InsertEnter * hi StatusLine ctermbg=02 ctermfg=00 term=none cterm=none
  au InsertLeave * hi StatusLine ctermbg=1 ctermfg=00 term=none cterm=none
endif

" COMPLETION COLORS
"hi Pmenu ctermbg=15 ctermfg=00
"hi PmenuSel ctermbg=3 ctermfg=00





" Vundle Stuff
" ---------------------------------------------------------------------------

filetype off                  " required!
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'


" Vundles...
Bundle 'scrooloose/nerdtree'
Bundle 'matze/vim-move'
Bundle "sjl/gundo.vim"
Bundle 'jlanzarotta/bufexplorer'
Bundle "plasticboy/vim-markdown"
Bundle 'tpope/vim-surround'
Bundle 'airblade/vim-gitgutter'

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install (update) bundles
" :BundleSearch(!) foo - search (or refresh cache first) for foo
" :BundleClean(!)      - confirm (or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle commands are not allowed.



" Shortcuts
" ---------------------------------------------------------------------------

" DISABLE THE ARROW KEYS - OH GOD...
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk

" Clear search highlighting
nnoremap <leader><space> :noh<cr>

" Quick-reload of this file
nnoremap reload :source ~/.vimrc<cr>

" Open NERDTree
nnoremap <leader>nt :NERDTreeToggle<cr>

" Gundo
nnoremap <F5> :GundoToggle<CR>

" When moving to the end of the document also move to the end of the line
nnoremap G G$

" toggle numbers
:nnoremap <leader>num :set invnumber<cr>

nnoremap mdown :set syntax=markdown<cr>

" Moving lines up and down
nnoremap <c-j> :m+<cr>
nnoremap <c-k> :m-2<cr>

" Some things to make editing in Insert Mode a little easier
" insert newline ahead of cursor
inoremap <c-k> <cr><c-o><bs>

" faster spelling correction
" Mark current position, jump to last misspelled word, offer corrections
inoremap <c-z> <esc>mxa<c-x>s
" leave insert mode, jump to x mark, re-enter insert mode
inoremap <c-l> <esc>`xa
