-- My Hammerspoon Menubar Item
-- ----------------------------------------------

hammerMenuTable = {}

hammerMenuIcon = [[ASCII:
...............
1.............1
7.............5
...............
....AD...FI....
...............
...............
....K.....L....
....N.....M....
...............
...............
....BC...GH....
...............
7.............5
3.............3
...............
]]

hammerMenu = hs.menubar.new()
hammerMenu:setIcon(hammerMenuIcon)

function hammerMenuSet()
  hammerMenu:setMenu(hammerMenuTable)
end
